//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcooSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanLoaiSach
    {
        public int ID_PhanLoai { get; set; }
        public Nullable<int> ID_Sach { get; set; }
        public Nullable<int> ID_TheLoai { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
