//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcooSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SachDaDatHang
    {
        public int ID { get; set; }
        public Nullable<int> idDonSach { get; set; }
        public Nullable<int> idSach { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual DonSach DonSach { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
